#!/usr/bin/env zsh
# This code was originally from
# https://gist.github.com/pogin503/ad1f14c09f3bf12b8096a644db237fd1

PORT="$1"
DIR="$2"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME"/jupyter
export JUPYTER_DATA_DIR="$XDG_DATA_HOME"/jupyter

source $HOME/.venv/bin/activate

jupyter lab --port "$PORT" --notebook-dir "$DIR"

deactivate
