[[plugins]]
repo = 'lervag/vimtex'
on_ft=['tex']
hook_source='''
  let g:vimtex_view_general_viewer = 'displayline'
  let g:vimtex_view_general_options = '@line @pdf @tex'
'''

[[plugins]]
repo = 'goerz/jupytext.vim'
on_ft = ['ipynb']
hook_source='''
" セルの区切り文字をVSCode互換の # %% に指定する
  let g:jupytext_fmt = 'py:percent'
" vimのPython向けシンタックスハイライトを有効にする
  let g:jupytext_filetype_map = {'py': 'python'}
'''
