[[plugins]]
repo = 'lervag/vimtex'
on_ft=['tex']
hook_source='''
  let g:tex_flavor = "latex"
  let g:vimtex_view_general_viewer = 'displayline'
  let g:vimtex_view_general_options = '@line @pdf @tex'
  let g:vimtex_compiler_latexmk = {
      \ 'options' : [
      \   '-verbose',
      \   '-file-line-error',
      \   '-synctex=1',
      \   '-interaction=nonstopmode',
      \ ]}
  let g:vimtex_compiler_progname = 'nvr'
'''
